#!/bin/bash

echo "🔧 Database URL Update Helper"
echo "============================="
echo ""
echo "From your Supabase dashboard, I can see you need to use the Transaction pooler connection."
echo ""
echo "Current DATABASE_URL format:"
echo "postgresql://postgres:[YOUR-PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
echo ""
echo "To update your .env.local file:"
echo ""
echo "1. Go to your Supabase dashboard"
echo "2. Copy the password from the Transaction pooler connection string"
echo "3. Replace [YOUR-PASSWORD] in the DATABASE_URL below"
echo ""
echo "Example:"
echo "DATABASE_URL=\"postgresql://postgres:your_actual_password_here@aws-0-us-east-1.pooler.supabase.com:6543/postgres\""
echo ""
echo "After updating .env.local, run:"
echo "   ./scripts/setup-database.sh"
echo ""
echo "Current .env.local DATABASE_URL:"
grep "DATABASE_URL" .env.local
